[package]
name = "c2a"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"

[dependencies]
base64 = { version = "0.22", default-features = false, features = ["alloc"] }
chrono = { version = "0.4", default-features = false, features = ["std"] }
getrandom = "0.4"
http-body-util = { version = "0.1", features = ["channel"] }
hyper = { version = "1", features = ["http1", "server"] }
hyper-util = { version = "0.1", features = ["tokio"] }
libc = { version = "0.2", default-features = false }
reqwest = { version = "0.13", default-features = false, features = ["form", "native-tls-no-alpn"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = { version = "0.11", default-features = false }
thiserror = "2"
tokio = { version = "1", default-features = false, features = ["net", "rt-multi-thread", "signal", "sync", "time"] }
